apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-backend-secret
type: Opaque
stringData:
  mysql-root-password: {{ .Values.mysql.rootPassword | quote }}
  mysql-password: {{ .Values.mysql.password | quote }}
  jwt-secret: {{ .Values.config.jwtSecret | quote }}
  oauth-client-id: {{ .Values.config.oauth.clientId | quote }}
  oauth-client-secret: {{ .Values.config.oauth.clientSecret | quote }}
  dify-api-key: {{ .Values.config.dify.apiKey | quote }}
